/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "commands": {
        "position": {
            "CREATED": string;
            "UPDATED": string;
            "ARCHIVED": string;
            "RESTORED": string;
            "PURGED": string;
        };
        "work-calendar": {
            "CREATED": string;
            "UPDATED": string;
            "ARCHIVED": string;
            "RESTORED": string;
            "PURGED": string;
        };
        "work-schedule": {
            "CREATED": string;
            "REVISION_CREATED": string;
            "ARCHIVED": string;
            "RESTORED": string;
            "PURGED": string;
        };
        "leave-policy": {
            "CREATED": string;
            "REVISION_CREATED": string;
            "ARCHIVED": string;
            "RESTORED": string;
            "PURGED": string;
        };
        "work-calendar-exception": {
            "CREATED": string;
            "UPDATED": string;
            "PURGED": string;
        };
        "employee": {
            "CREATED": string;
            "UPDATED": string;
            "ACCOUNT_LINKED": string;
            "ACCOUNT_UNLINKED": string;
            "ARCHIVED": string;
            "RESTORED": string;
            "HRBP_UPDATED": string;
        };
        "hr-request": {
            "CREATED": string;
            "UPDATED": string;
            "SUBMITTED": string;
            "WITHDRAWN": string;
        };
        "hr-approval-step": {
            "REASSIGNED": string;
            "APPROVED": string;
            "REJECTED": string;
            "RETURNED": string;
        };
    };
    "db": {
        "NOT_FOUND": string;
        "UNIQUE_VIOLATION": string;
        "FK_VIOLATION": string;
        "NOT_NULL_VIOLATION": string;
        "DEADLOCK": string;
        "LOCK_TIMEOUT": string;
        "CONNECTION_LOST": string;
        "INTERNAL_DRIVER_ERROR": string;
    };
    "entities": {
        "position": {
            "CANNOT_UPDATE_ARCHIVED": string;
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
            "OPERATION_PENDING": string;
        };
        "work-calendar": {
            "CANNOT_UPDATE_ARCHIVED": string;
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
        };
        "work-calendar-exception": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "ORGANIZATION_MISMATCH": string;
        };
        "work-schedule": {
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
            "CANNOT_UPDATE_ARCHIVED": string;
            "NO_CHANGES_DETECTED": string;
        };
        "leave-policy": {
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
            "CANNOT_UPDATE_ARCHIVED": string;
            "NO_CHANGES_DETECTED": string;
        };
        "employee": {
            "CANNOT_UPDATE_ARCHIVED": string;
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "ACCOUNT_ALREADY_LINKED": string;
            "ACCOUNT_NOT_LINKED": string;
            "INVALID_HRBP": string;
            "INVALID_STATUS": string;
            "INVALID_PERIOD": string;
            "ORGANIZATION_MISMATCH": string;
            "ARCHIVED_TERMS": string;
        };
        "position-assignment": {
            "INVALID_STATUS": string;
            "INVALID_PERIOD": string;
            "REQUEST_MISMATCH": string;
            "ORGANIZATION_MISMATCH": string;
            "INACTIVE_REFERENCE": string;
            "PLACEMENT_MISMATCH": string;
        };
        "employment": {
            "ORGANIZATION_MISMATCH": string;
            "REQUEST_MISMATCH": string;
        };
        "hr-request": {
            "INVALID_STATUS": string;
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "INVALID_EXECUTION_STATUS": string;
            "APPLICATION_NOT_DUE": string;
            "STALE_REVISION": string;
            "ORGANIZATION_MISMATCH": string;
            "REQUEST_MISMATCH": string;
        };
        "hr-approval-step": {
            "INVALID_STATUS": string;
            "INACTIVE_ASSIGNEE": string;
            "NO_CHANGES_DETECTED": string;
            "ORGANIZATION_MISMATCH": string;
            "STALE_REVISION": string;
            "INVALID_REQUEST_STATUS": string;
        };
        "hr-approval-decision": {
            "ORGANIZATION_MISMATCH": string;
            "STALE_REVISION": string;
            "INVALID_ACTOR": string;
            "INVALID_REQUEST_STATUS": string;
            "INVALID_STATUS": string;
        };
        "absence": {
            "INVALID_STATUS": string;
            "NO_CHANGES_DETECTED": string;
            "REQUEST_MISMATCH": string;
            "INVALID_REQUEST_STATUS": string;
            "ORGANIZATION_MISMATCH": string;
            "INVALID_POOL": string;
        };
        "leave-ledger-entry": {
            "ORGANIZATION_MISMATCH": string;
            "REQUEST_MISMATCH": string;
            "POOL_MISMATCH": string;
            "INVALID_POOL": string;
            "INVALID_REVERSAL": string;
        };
    };
    "global": {
        "throttle": string;
    };
    "guard": {
        "permission": {
            "ACCOUNT_REQUIRED": string;
            "REALM_REQUIRED": string;
            "REALM_SCOPE_MISSING": string;
            "REALM_OUT_OF_SESSION_SCOPE": string;
            "GLOBAL_SCOPE_REQUIRES_DIRECT_LOGIN": string;
            "INSUFFICIENT_PERMISSIONS": string;
        };
        "authn": {
            "TOKEN_MISSING": string;
            "MALFORMED_AUTHORIZATION": string;
            "SESSION_REVOKED": string;
        };
        "reauthentication": {
            "REAUTHENTICATION_REQUIRED": string;
            "NOT_AUTHENTICATED": string;
        };
    };
    "services": {
        "organization": {
            "REALM_MISMATCH": string;
        };
        "kafka-incoming": {
            "EVENT_MISSING": string;
        };
        "schema-registry": {
            "ENCODE_FAILED": string;
            "DECODE_FAILED": string;
            "MESSAGE_INVALID": string;
        };
        "jwt": {
            "INVALID_ACCESS_TOKEN": string;
        };
        "vault": {
            "REQUEST_FAILED": string;
            "INVALID_SIGNATURE": string;
        };
        "work-schedule": {
            "STALE_REVISION": string;
        };
        "leave-policy": {
            "STALE_REVISION": string;
        };
        "leave-ledger-entry": {
            "INVALID_REVERSAL": string;
        };
        "hr-request": {
            "EMPTY_APPROVAL_ROUTE": string;
            "ASSIGNEE_NOT_FOUND": string;
        };
    };
    "validator": {
        "REQUIRED": string;
        "IS_OBJECT": string;
        "IS_STRING": string;
        "LENGTH": string;
        "MIN_LENGTH": string;
        "MAX_LENGTH": string;
        "ARRAY_MIN_SIZE": string;
        "ARRAY_MAX_SIZE": string;
        "MATCHES": string;
        "IS_EMAIL": string;
        "IS_UUID": string;
        "IS_PHONE": string;
        "IS_NUMBER": string;
        "IS_INT": string;
        "IS_POSITIVE": string;
        "MIN": string;
        "MAX": string;
        "IS_DECIMAL": string;
        "IS_BOOLEAN": string;
        "IS_DATE": string;
        "IS_ENUM": string;
        "IS_ARRAY": string;
        "ARRAY_UNIQUE": string;
        "NESTED": string;
        "IS_IN": string;
        "IS_ORDINAL": string;
        "NOT_EQUAL_TO": string;
        "IS_MS_STRING": string;
        "COMMON_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
